// Generated by CoffeeScript 1.3.3
(function() {

  doctype(5);

  html({
    lang: 'en'
  }, function() {
    head(function() {
      title('scrundle.me!');
      meta({
        charset: 'utf-8'
      });
      meta({
        name: "viewport",
        content: "width=device-width, initial-scale=1.0"
      });
      link({
        rel: 'stylesheet',
        href: '/css/bootstrap.min.css'
      });
      return link({
        rel: 'stylesheet',
        href: '/css/index.css'
      });
    });
    return body(function() {
      div({
        "class": 'container main'
      }, function() {});
      script({
        type: 'text/javascript',
        src: '/js/utils.js'
      });
      script({
        type: 'text/javascript',
        src: '/ck.js'
      });
      script({
        type: 'text/javascript',
        src: '/js/bootstrap.min.js'
      });
      script({
        type: 'text/javascript',
        src: '/socket.io/socket.io.js'
      });
      return script({
        type: 'text/javascript',
        src: '/js/client.js'
      });
    });
  });

}).call(this);
